/*
    Project: WARP | (C) Noctefugia, March 2024
    File: mb_core.h
    Description: M&B plugins core header
*/

#include <time.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

//! SYSTEM DEFINES
#define HOOKED_OPCODE       3026        // WSE2 opcode for user hooks
#define MIN_USER_CODE       0xFFFFFFFF  // Minimum user opcode value
#define PRINT_BUFF_SZ       1024        // Size for all printf buffers
#define ALIGN(val)          __attribute__((aligned(val)))
#define MB_API              __attribute__((dllimport)) MB_ERROR
#define MBEX_API extern     __attribute__((dllimport))
#define ENSURE(expr)        do { if (!(expr)) return __LINE__; } while (0)
#define ENSURE_SZ(obj, sz)  do { if (sizeof(obj) != sz) return __LINE__; } while (0)
#define ENSURE_PLUGIN(fn)   do { pCodeList[index] = fn(&pCallList[index++]); if (index >= *pListSz) return __LINE__; } while (0)
#define ENSURE_FN(expr)     do { if (expr) return __LINE__; } while (0)

//! TYPEDEFS
typedef unsigned char byte;             // 1-byte type
typedef byte bool;                      // 1-byte bool
#define true 1                          // True
#define false 0                         // False
typedef unsigned int uint;              // Unsigned int type
typedef uint MB_ERROR;                  // Error code type
typedef long long int64;                // 64-bit signed int type
typedef unsigned long long uint64;      // 64-bit unsigned int type
typedef uint64 MB_CODENAME;             // Unique codename for plugin

//! ENGINE API (generated by WARP library)
#include "..\mb_api\mb_defs.h"

//! EXTENSION API (provided by WARP library)
MBEX_API const byte MBEX_VerMajor;                  // WARP version major
MBEX_API const byte MBEX_VerMinor;                  // WARP version minor
MBEX_API const byte MBEX_VerPatch;                  // WARP version patch  
MBEX_API void MBEX_Print(char *pMsg);               // Print to console
MBEX_API void MBEX_Sleep(uint ms);                  // Sleep (freeze thread for milliseconds)
MBEX_API uint MBEX_FindSymbol(const char *pName);   // Find symbol address by name in PDB-info

#define MBEX_PRINTF(format, ...) do { char tmpwpBuff[PRINT_BUFF_SZ]; snprintf(tmpwpBuff, PRINT_BUFF_SZ, "[MB] " format, ## __VA_ARGS__); MBEX_Print(tmpwpBuff); } while(0)

//! UTIL MACROS
#define UTIL_STRHLP(x) #x                                                   // Helper to convert a macro argument to a string
#define UTIL_STR(x) UTIL_STRHLP(x)                                          // Convert a macro argument to a string
#define UTIL_IDENT(x) x                                                     // Return its argument
#define UTIL_BSET(value, bits) ((value) |= (bits))							// Set bits in value
#define UTIL_BCLR(value, bits) ((value) &= (~(bits)))						// Clear bits in value
#define UTIL_BINV(value, bits) ((value) ^= (bits))							// Invert bits
#define UTIL_IS_BSET(value, bits) (((value) & (bits)) == (bits))			// Check if bits in value are set - true/false
#define UTIL_IS_BCLR(value, bits) (!UTIL_BITS_IS_SET(value, bits))			// Check if bits in value are clear - true/false
#define UTIL_LOW32(value) ((value) & 0xFFFFFFFF)                            // Extract lower 32 bits of 64 bit value
#define UTIL_UP32(value) (((value) >> 32) & 0xFFFFFFFF)                     // Extract upper 32 bits of 64 bit value
#define UTIL_GETBYTE(value, n) (((value) >> (n * 8)) & 0xFF)
#define UTIL_ZERO(object) memset(&object, 0, sizeof(object))                // Quickly set all struct/array members to zero. DONT USE WITH POINTERS!

//! UTIL FUNCTIONS
static inline float UTIL_DegToRad(float deg) 					{ return (float)((deg) * M_PI / 180.0f); }												// Convert degrees to radians
static inline float	UTIL_RadToDeg(float rad)					{ return (float)((rad) * 180.0f / M_PI); }												// Convert radians to degrees
static inline float UTIL_ConstrainDeg(float angle)				{ angle = fmod(angle, 360.0f); if (angle < 0.0f) { angle += 360.0f; } return angle; }	// Constrain angle 0-360
static inline float UTIL_RotateDeg(float value, float angle)	{ value += angle; return UTIL_ConstrainDeg(value); }									// Rotate in degrees with constrain
static inline int	UTIL_RandInt(int min, int max)				{ return min + rand() % (max - min + 1); }												// Generate random number within the specified range [min, max]
static inline float UTIL_RandFloat(float min, float max)		{ float scale = rand() / (float) RAND_MAX; return min + scale * (max - min); }			// Generate random float number within the specified range [min, max]

//! COMMON ADDONS
#include "mb_asm.c"
#include "mb_utils.c"	

